import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/../providers/modal-provider";
import { ToasterProvider } from "@/../../providers/toast-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ameytech-admin",
  description: "Generated by mohk",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <html lang="en">
        <body className={inter.className}>
        <ClerkProvider>
          {/* from providers>toast-provider */}
          <ToasterProvider />
          {/* from providers>modal-provider */}
          <ModalProvider />
          {children}
          </ClerkProvider>
          
          </body>
      </html>
    

  );
}
